name: Java CI with Gradle
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  test:
    name: Running Units Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup docker
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Run unit test
        run: ./gradlew clean check
